version:  '3.7'
services: 
  databaseService:
    image: 'mongo'
    container_name: 'reconcile-db-container'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
      - MONGO_DATABASE_USER=${MONGO_DATABASE_USER}
      - MONGO_DATABASE_PASSWORD=${MONGO_DATABASE_PASSWORD}
    volumes: 
      - ./project_db/localdb/datadir:/data/db
      - ./project_db/initscrpts/dbcreations-with-migrations-runsOnce/init-scripts:/docker-entrypoint-initdb.d
      - ./project_db/initscrpts/dbcreations-with-migrations-runsOnce/migrations/up:/migrations
    ports: 
      - '${MONGO_PORT}:27017'
  api: 
    restart: always
    build:
      context: ./apis
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./apis:/app
    environment: 
      - API_SERVICE_URL=${EXTERNALWEBHOST}/api/
      - MONGO_SERVICE_URI=${MONGO_SERVICE_URI}
      - JWT_SECRET=${JWT_SECRET}
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - '${EXTERNALWEBPORT}:80'