name: CI_CD

on: [push]

jobs:

  unit_test_client:
    runs-on: ubuntu-latest
    container:
      image: node:alpine

    steps:
      - name: Pull latest code
        uses: actions/checkout@master
      
      - name: Install & Tests
        working-directory: ./client
        run: |
          npm install
          npm test -- --coverage --watchAll=false
  
  unit_test_api:
    runs-on: ubuntu-latest
    container:
      image: node:alpine

    steps:
      - name: Pull latest code
        uses: actions/checkout@master
      
      - name: Install & Tests
        working-directory: ./apis
        run: |
          npm install
          npm test -- --coverage --watchAll=false
